package com.await.product_management_rest_swagger.model; // Package where the model class is located

import jakarta.persistence.Entity; // Importing Entity annotation to mark this class as a JPA entity
import jakarta.persistence.GeneratedValue; // Importing annotation for auto-generating primary key values
import jakarta.persistence.GenerationType; // Importing strategy for how the primary key values are generated
import jakarta.persistence.Id; // Importing Id annotation to mark the primary key
import lombok.Data; // Importing Lombok's Data annotation for generating boilerplate code (getters, setters, equals, hashCode, toString)

@Entity // Marking this class as a JPA entity that will be mapped to a database table
@Data // Lombok annotation to automatically generate getters, setters, and other common methods
public class Category {

    @Id // Denotes this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the ID will be auto-generated by the database
    private Long id;

    // Field representing the name of the category
    private String name;
}
